name: Living with Insulin Resistance
favicon: null
layout_spectrum: 0.999
typography_spectrum: 0.497
title: Living with Insulin Resistance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f6f2'
    - '#0b0b0b'
    - '#afaaa6'
    - '#6d432b'
    - '#9b8574'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
