name: Living with Insulin Resistance
favicon: null
layout_spectrum: 0.741
typography_spectrum: 0.1865146216005087
title: Living with Insulin Resistance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8c3b9'
    - '#b3a7aa'
    - '#2c153c'
    - '#ad667f'
    - '#be8d88'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
